name: Start SSH and Web Server with Ngrok

on: push

jobs:
  run-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar Docker corretamente
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io jq

      - name: Construir e rodar o container
        run: |
          docker build -t my-ssh-ngrok .
          docker run -d --name ssh-server -p 22:22 -p 80:80 -p 8080:8080 my-ssh-ngrok

      - name: Instalar e configurar o Ngrok
        run: |
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt update && sudo apt install -y ngrok

      - name: Criar configuração do Ngrok
        run: |
          mkdir -p ~/.ngrok2
          cat <<EOF > ~/.ngrok2/ngrok.yml
          authtoken: ${{ secrets.NGROK_AUTH_TOKEN }}
          tunnels:
            web:
              proto: http
              addr: 80
            terminal:
              proto: http
              addr: 8080
          EOF

      - name: Iniciar Ngrok
        run: ngrok start --all --config ~/.ngrok2/ngrok.yml &

      - name: Exibir URLs do Ngrok
        run: |
          sleep 5
          curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[] | "\(.name): \(.public_url)"'

      - name: Manter execução ativa
        run: sleep infinity
