name: Deploy SSH VPS with Ngrok

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Verify Docker is running
        run: docker ps

      - name: Create and Start SSH Docker Container
        run: |
          docker run -d --name minha-vps -p 2222:22 -e ROOT_PASS=s3nh@forte rastasheep/ubuntu-sshd
          sleep 5  # Aguarda o SSH iniciar

      - name: Install jq (for JSON processing)
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Install Ngrok
        run: |
          if ! command -v ngrok &> /dev/null; then
            curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
            echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
            sudo apt update && sudo apt install -y ngrok
          fi

      - name: Authenticate Ngrok
        run: ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

      - name: Start Ngrok Tunnel for SSH
        run: ngrok tcp 2222 > /dev/null &

      - name: Keep the Job Alive
        run: tail -f /dev/null
