name: Deploy Ubuntu SSH with Ngrok

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Configurar Ngrok
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
      run: |
        wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-stable-linux-amd64.zip
        unzip ngrok-stable-linux-amd64.zip
        chmod +x ngrok
        ./ngrok authtoken $NGROK_AUTH_TOKEN

    - name: Construir e rodar o contêiner Docker
      run: |
        docker build -t ubuntu-ssh-ngrok .
        docker run -d -p 22:22 ubuntu-ssh-ngrok

    - name: Expor SSH via Ngrok
      run: ./ngrok tcp 22
