name: Docker SSH with Ngrok

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t ubuntu-ssh-ngrok .

    - name: Run Docker container
      run: |
        docker run -d --name ssh_container ubuntu-ssh-ngrok
        sleep 10  # Espera o Ngrok iniciar
        docker logs ssh_container 2>&1 | grep "tcp://"  # Captura a URL do Ngrok
